## YAML Template.
---
spring:
    application:
        name: zuulserver
        
server:
    port: 5555
    
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    
zuul.sensitiveHeaders: Cookie,Set-Cookie

 #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.notix: DEBUG