## YAML Template.
---
version: '2'
services:
    
    eurekaserver:
        image: notix/eurekaserver:n1
        ports:
            - "8761:8761"

    configserver:
        image: notix/configserver:n1
        ports:
            - "8888:8888"

        environment:
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT: "8761"
            ENCRYPT_KEY:       "IMSYMMETRIC"
            
    zuulserver:
        image: notix/zuulserver:n1
        ports:
            - "5555:5555"
        environment:
            PROFILE: "default"
            SERVER_PORT: "5555"
            CONFIGSERVER_PORT: 8888
            EUREKASERVER_PORT: 8761
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

    employeeservice:
        image: notix/employeeservice:n1
        ports:
            - "8085:8085"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8085"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"

            ENCRYPT_KEY:       "IMSYMMETRIC"
        links:
            - configserver
            - eurekaserver
            - zuulserver

    empservice:
        image: notix/empservice:n1
        ports:
            - "8000:8000"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8000"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"

            ENCRYPT_KEY:       "IMSYMMETRIC"
        links:
            - configserver
            - eurekaserver
            - zuulserver

    loginservice:
        image: notix/loginservice:n1
        ports:
            - "8005:8005"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8005"
            CONFIGSERVER_URI: "http://configserver:8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT:   "8761"
            CONFIGSERVER_PORT:   "8888"
            ZUULSERVER_PORT:     "5555"

            ENCRYPT_KEY:       "IMSYMMETRIC"
        links:
            - configserver
            - eurekaserver
            - zuulserver