## YAML Template.
---
server:
    port: 8085

security:
    oauth2:
        resource:
            userInfoUri: http://localhost:8901/auth/user
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        
spring:
    application:
        name: employeeservice
    jpa:
      showSql: true
      
    h2:
     console:
        enabled: true
        
    cloud:
        config:
            enabled: true
