## YAML Template.
---
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
    port: 8005
    
spring:
  application:
    name: login-service
  profiles:
    active:
      default