## YAML Template.
---
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
    port: 8005
    
spring:
  application:
    name: loginservice
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true
      
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secretcode
      accessTokenUri: http://localhost:8901/auth/oauth/token
      userAuthorizationUri: http://localhost:8901/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8901/auth/user      

#security:
 #oauth2:
  #resource:
   # userInfoUri: http://localhost:8901/auth/user