## YAML Template.
---
spring:
    application:
        name: configserver
    cloud:
        config:
            discovery:
                enabled: true
            server:
                encrypt.enabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/